// flow-typed signature: 9e19e8e06ec1306bb03dff5706c3ef0d
// flow-typed version: <<STUB>>/electron-log_v^1.2.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-log/index' {
  declare module.exports: $Exports<'electron-log'>;
}
declare module 'electron-log/index.js' {
  declare module.exports: $Exports<'electron-log'>;
}
