// flow-typed signature: b19070b145c54ac7f7b9f71e12f12de4
// flow-typed version: <<STUB>>/electron-context-menu_v^0.8.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-context-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-context-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-context-menu/index' {
  declare module.exports: $Exports<'electron-context-menu'>;
}
declare module 'electron-context-menu/index.js' {
  declare module.exports: $Exports<'electron-context-menu'>;
}
