// flow-typed signature: dd110e98a6379f33c4ad5b7f52e8e203
// flow-typed version: <<STUB>>/enchannel_v^1.1.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enchannel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'enchannel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enchannel/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enchannel/index' {
  declare module.exports: $Exports<'enchannel'>;
}
declare module 'enchannel/index.js' {
  declare module.exports: $Exports<'enchannel'>;
}
declare module 'enchannel/test/index.js' {
  declare module.exports: $Exports<'enchannel/test/index'>;
}
