// flow-typed signature: 23669a6ce2fc882e556b886f39b345c0
// flow-typed version: <<STUB>>/jsonschema_v^1.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonschema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonschema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonschema/lib/attribute' {
  declare module.exports: any;
}

declare module 'jsonschema/lib/helpers' {
  declare module.exports: any;
}

declare module 'jsonschema/lib/index' {
  declare module.exports: any;
}

declare module 'jsonschema/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonschema/lib/attribute.js' {
  declare module.exports: $Exports<'jsonschema/lib/attribute'>;
}
declare module 'jsonschema/lib/helpers.js' {
  declare module.exports: $Exports<'jsonschema/lib/helpers'>;
}
declare module 'jsonschema/lib/index.js' {
  declare module.exports: $Exports<'jsonschema/lib/index'>;
}
declare module 'jsonschema/lib/validator.js' {
  declare module.exports: $Exports<'jsonschema/lib/validator'>;
}
