// flow-typed signature: ece2cab61124ce02fe99e520065a41ce
// flow-typed version: <<STUB>>/jsontableschema_v^0.2.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsontableschema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsontableschema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsontableschema/dist/jsontableschema' {
  declare module.exports: any;
}

declare module 'jsontableschema/dist/jsontableschema.min' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/constraints' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/field' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/index' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/infer' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/schema' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/table' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/types' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/utilities' {
  declare module.exports: any;
}

declare module 'jsontableschema/lib/validate' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/constraints' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/field' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/index' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/infer' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/schema' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/table' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/types' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/utilities' {
  declare module.exports: any;
}

declare module 'jsontableschema/src/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsontableschema/dist/jsontableschema.js' {
  declare module.exports: $Exports<'jsontableschema/dist/jsontableschema'>;
}
declare module 'jsontableschema/dist/jsontableschema.min.js' {
  declare module.exports: $Exports<'jsontableschema/dist/jsontableschema.min'>;
}
declare module 'jsontableschema/lib/constraints.js' {
  declare module.exports: $Exports<'jsontableschema/lib/constraints'>;
}
declare module 'jsontableschema/lib/field.js' {
  declare module.exports: $Exports<'jsontableschema/lib/field'>;
}
declare module 'jsontableschema/lib/index.js' {
  declare module.exports: $Exports<'jsontableschema/lib/index'>;
}
declare module 'jsontableschema/lib/infer.js' {
  declare module.exports: $Exports<'jsontableschema/lib/infer'>;
}
declare module 'jsontableschema/lib/schema.js' {
  declare module.exports: $Exports<'jsontableschema/lib/schema'>;
}
declare module 'jsontableschema/lib/table.js' {
  declare module.exports: $Exports<'jsontableschema/lib/table'>;
}
declare module 'jsontableschema/lib/types.js' {
  declare module.exports: $Exports<'jsontableschema/lib/types'>;
}
declare module 'jsontableschema/lib/utilities.js' {
  declare module.exports: $Exports<'jsontableschema/lib/utilities'>;
}
declare module 'jsontableschema/lib/validate.js' {
  declare module.exports: $Exports<'jsontableschema/lib/validate'>;
}
declare module 'jsontableschema/src/constraints.js' {
  declare module.exports: $Exports<'jsontableschema/src/constraints'>;
}
declare module 'jsontableschema/src/field.js' {
  declare module.exports: $Exports<'jsontableschema/src/field'>;
}
declare module 'jsontableschema/src/index.js' {
  declare module.exports: $Exports<'jsontableschema/src/index'>;
}
declare module 'jsontableschema/src/infer.js' {
  declare module.exports: $Exports<'jsontableschema/src/infer'>;
}
declare module 'jsontableschema/src/schema.js' {
  declare module.exports: $Exports<'jsontableschema/src/schema'>;
}
declare module 'jsontableschema/src/table.js' {
  declare module.exports: $Exports<'jsontableschema/src/table'>;
}
declare module 'jsontableschema/src/types.js' {
  declare module.exports: $Exports<'jsontableschema/src/types'>;
}
declare module 'jsontableschema/src/utilities.js' {
  declare module.exports: $Exports<'jsontableschema/src/utilities'>;
}
declare module 'jsontableschema/src/validate.js' {
  declare module.exports: $Exports<'jsontableschema/src/validate'>;
}
