// flow-typed signature: 22f982c19613d2572a312bb53e5b0b0f
// flow-typed version: <<STUB>>/react-katex_v2.0.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-katex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-katex" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-katex/coverage/block-navigation" {
  declare module.exports: any;
}

declare module "react-katex/coverage/prettify" {
  declare module.exports: any;
}

declare module "react-katex/coverage/sorter" {
  declare module.exports: any;
}

declare module "react-katex/dist/react-katex" {
  declare module.exports: any;
}

declare module "react-katex/dist/react-katex.min" {
  declare module.exports: any;
}

declare module "react-katex/rollup.config" {
  declare module.exports: any;
}

declare module "react-katex/src/BlockMath" {
  declare module.exports: any;
}

declare module "react-katex/src/createMathComponent" {
  declare module.exports: any;
}

declare module "react-katex/src/index" {
  declare module.exports: any;
}

declare module "react-katex/src/InlineMath" {
  declare module.exports: any;
}

declare module "react-katex/test/components/BlockMath.spec" {
  declare module.exports: any;
}

declare module "react-katex/test/components/InlineMath.spec" {
  declare module.exports: any;
}

declare module "react-katex/test/sharedExamples" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-katex/coverage/block-navigation.js" {
  declare module.exports: $Exports<"react-katex/coverage/block-navigation">;
}
declare module "react-katex/coverage/prettify.js" {
  declare module.exports: $Exports<"react-katex/coverage/prettify">;
}
declare module "react-katex/coverage/sorter.js" {
  declare module.exports: $Exports<"react-katex/coverage/sorter">;
}
declare module "react-katex/dist/react-katex.js" {
  declare module.exports: $Exports<"react-katex/dist/react-katex">;
}
declare module "react-katex/dist/react-katex.min.js" {
  declare module.exports: $Exports<"react-katex/dist/react-katex.min">;
}
declare module "react-katex/rollup.config.js" {
  declare module.exports: $Exports<"react-katex/rollup.config">;
}
declare module "react-katex/src/BlockMath.js" {
  declare module.exports: $Exports<"react-katex/src/BlockMath">;
}
declare module "react-katex/src/createMathComponent.js" {
  declare module.exports: $Exports<"react-katex/src/createMathComponent">;
}
declare module "react-katex/src/index.js" {
  declare module.exports: $Exports<"react-katex/src/index">;
}
declare module "react-katex/src/InlineMath.js" {
  declare module.exports: $Exports<"react-katex/src/InlineMath">;
}
declare module "react-katex/test/components/BlockMath.spec.js" {
  declare module.exports: $Exports<
    "react-katex/test/components/BlockMath.spec"
  >;
}
declare module "react-katex/test/components/InlineMath.spec.js" {
  declare module.exports: $Exports<
    "react-katex/test/components/InlineMath.spec"
  >;
}
declare module "react-katex/test/sharedExamples.js" {
  declare module.exports: $Exports<"react-katex/test/sharedExamples">;
}
