// flow-typed signature: 1dc8b9739e592e4f2b889ef2fa207e37
// flow-typed version: <<STUB>>/rehype-katex_v1.1.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-katex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rehype-katex" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "rehype-katex/index" {
  declare module.exports: $Exports<"rehype-katex">;
}
declare module "rehype-katex/index.js" {
  declare module.exports: $Exports<"rehype-katex">;
}
