// flow-typed signature: 5e00a76384ac402aedb0a9064fd8db9c
// flow-typed version: <<STUB>>/remark-math_v1.0.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-math'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "remark-math" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "remark-math/block" {
  declare module.exports: any;
}

declare module "remark-math/inline" {
  declare module.exports: any;
}

// Filename aliases
declare module "remark-math/block.js" {
  declare module.exports: $Exports<"remark-math/block">;
}
declare module "remark-math/index" {
  declare module.exports: $Exports<"remark-math">;
}
declare module "remark-math/index.js" {
  declare module.exports: $Exports<"remark-math">;
}
declare module "remark-math/inline.js" {
  declare module.exports: $Exports<"remark-math/inline">;
}
