// flow-typed signature: d66449e2c390970c7c4fee9b8e1f044f
// flow-typed version: <<STUB>>/rimraf_v^2.5.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rimraf/bin' {
  declare module.exports: any;
}

declare module 'rimraf/rimraf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rimraf/bin.js' {
  declare module.exports: $Exports<'rimraf/bin'>;
}
declare module 'rimraf/rimraf.js' {
  declare module.exports: $Exports<'rimraf/rimraf'>;
}
