// flow-typed signature: 59ee5200511244213673713adbfc52d7
// flow-typed version: <<STUB>>/spawn-rx_v^2.0.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spawn-rx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spawn-rx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spawn-rx/lib/index' {
  declare module.exports: any;
}

declare module 'spawn-rx/src/index' {
  declare module.exports: any;
}

declare module 'spawn-rx/test/asserttest' {
  declare module.exports: any;
}

declare module 'spawn-rx/test/spawn' {
  declare module.exports: any;
}

declare module 'spawn-rx/test/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spawn-rx/lib/index.js' {
  declare module.exports: $Exports<'spawn-rx/lib/index'>;
}
declare module 'spawn-rx/src/index.js' {
  declare module.exports: $Exports<'spawn-rx/src/index'>;
}
declare module 'spawn-rx/test/asserttest.js' {
  declare module.exports: $Exports<'spawn-rx/test/asserttest'>;
}
declare module 'spawn-rx/test/spawn.js' {
  declare module.exports: $Exports<'spawn-rx/test/spawn'>;
}
declare module 'spawn-rx/test/support.js' {
  declare module.exports: $Exports<'spawn-rx/test/support'>;
}
