// flow-typed signature: caf46ff14e47fca34569f2e8bc5cff2d
// flow-typed version: <<STUB>>/spawnteract_v^2.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spawnteract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spawnteract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spawnteract/test/spawn_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spawnteract/index' {
  declare module.exports: $Exports<'spawnteract'>;
}
declare module 'spawnteract/index.js' {
  declare module.exports: $Exports<'spawnteract'>;
}
declare module 'spawnteract/test/spawn_spec.js' {
  declare module.exports: $Exports<'spawnteract/test/spawn_spec'>;
}
