// flow-typed signature: 336fdec7c203e0870e5c53c2767e6ee9
// flow-typed version: <<STUB>>/vega-embed_v^2.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-embed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-embed/scripts/schema' {
  declare module.exports: any;
}

declare module 'vega-embed/src/embed' {
  declare module.exports: any;
}

declare module 'vega-embed/src/parameter' {
  declare module.exports: any;
}

declare module 'vega-embed/src/post' {
  declare module.exports: any;
}

declare module 'vega-embed/vega-embed' {
  declare module.exports: any;
}

declare module 'vega-embed/vega-embed.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-embed/scripts/schema.js' {
  declare module.exports: $Exports<'vega-embed/scripts/schema'>;
}
declare module 'vega-embed/src/embed.js' {
  declare module.exports: $Exports<'vega-embed/src/embed'>;
}
declare module 'vega-embed/src/parameter.js' {
  declare module.exports: $Exports<'vega-embed/src/parameter'>;
}
declare module 'vega-embed/src/post.js' {
  declare module.exports: $Exports<'vega-embed/src/post'>;
}
declare module 'vega-embed/vega-embed.js' {
  declare module.exports: $Exports<'vega-embed/vega-embed'>;
}
declare module 'vega-embed/vega-embed.min.js' {
  declare module.exports: $Exports<'vega-embed/vega-embed.min'>;
}
