// flow-typed signature: 81d150ad6c03edfb536fb49c50f48347
// flow-typed version: <<STUB>>/vega-lite_v^1.3.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-lite/_site/examples/examples.test' {
  declare module.exports: any;
}

declare module 'vega-lite/examples/examples.test' {
  declare module.exports: any;
}

declare module 'vega-lite/site/static/main' {
  declare module.exports: any;
}

declare module 'vega-lite/site/static/test-gallery' {
  declare module.exports: any;
}

declare module 'vega-lite/src/aggregate' {
  declare module.exports: any;
}

declare module 'vega-lite/src/axis' {
  declare module.exports: any;
}

declare module 'vega-lite/src/bin' {
  declare module.exports: any;
}

declare module 'vega-lite/src/channel' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/axis' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/common' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/compile' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/config' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/bin' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/colorrank' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/data' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/filter' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/formatparse' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/formula' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/nonpositivenullfilter' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/nullfilter' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/source' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/stackscale' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/summary' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/timeunit' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/data/timeunitdomain' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/facet' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/layer' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/layout' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/legend' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/area' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/bar' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/line' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/mark' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/point' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/rule' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/text' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/mark/tick' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/model' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/scale' {
  declare module.exports: any;
}

declare module 'vega-lite/src/compile/unit' {
  declare module.exports: any;
}

declare module 'vega-lite/src/config' {
  declare module.exports: any;
}

declare module 'vega-lite/src/data' {
  declare module.exports: any;
}

declare module 'vega-lite/src/datetime' {
  declare module.exports: any;
}

declare module 'vega-lite/src/encoding' {
  declare module.exports: any;
}

declare module 'vega-lite/src/facet' {
  declare module.exports: any;
}

declare module 'vega-lite/src/fielddef' {
  declare module.exports: any;
}

declare module 'vega-lite/src/filter' {
  declare module.exports: any;
}

declare module 'vega-lite/src/legend' {
  declare module.exports: any;
}

declare module 'vega-lite/src/mark' {
  declare module.exports: any;
}

declare module 'vega-lite/src/scale' {
  declare module.exports: any;
}

declare module 'vega-lite/src/shorthand' {
  declare module.exports: any;
}

declare module 'vega-lite/src/sort' {
  declare module.exports: any;
}

declare module 'vega-lite/src/spec' {
  declare module.exports: any;
}

declare module 'vega-lite/src/stack' {
  declare module.exports: any;
}

declare module 'vega-lite/src/timeunit' {
  declare module.exports: any;
}

declare module 'vega-lite/src/transform' {
  declare module.exports: any;
}

declare module 'vega-lite/src/type' {
  declare module.exports: any;
}

declare module 'vega-lite/src/util' {
  declare module.exports: any;
}

declare module 'vega-lite/src/validate' {
  declare module.exports: any;
}

declare module 'vega-lite/src/vega.schema' {
  declare module.exports: any;
}

declare module 'vega-lite/src/vl' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/axis.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/common.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/compile.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/config.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data/datatestutil' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data/filter.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data/formatparse.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data/timeunit.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/data/timeunitdomain.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/facet.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/layer.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/layout.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/legend.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/area.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/bar.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/line.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/mark.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/point.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/text.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/mark/tick.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/scale.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/timeunit.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/compile/unit.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/datetime.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/fielddef.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/filter.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/schema.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/spec.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/stack.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/timeunit.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/type.test' {
  declare module.exports: any;
}

declare module 'vega-lite/test/util' {
  declare module.exports: any;
}

declare module 'vega-lite/test/validate.test' {
  declare module.exports: any;
}

declare module 'vega-lite/vega-lite' {
  declare module.exports: any;
}

declare module 'vega-lite/vega-lite.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-lite/_site/examples/examples.test.js' {
  declare module.exports: $Exports<'vega-lite/_site/examples/examples.test'>;
}
declare module 'vega-lite/examples/examples.test.js' {
  declare module.exports: $Exports<'vega-lite/examples/examples.test'>;
}
declare module 'vega-lite/site/static/main.js' {
  declare module.exports: $Exports<'vega-lite/site/static/main'>;
}
declare module 'vega-lite/site/static/test-gallery.js' {
  declare module.exports: $Exports<'vega-lite/site/static/test-gallery'>;
}
declare module 'vega-lite/src/aggregate.js' {
  declare module.exports: $Exports<'vega-lite/src/aggregate'>;
}
declare module 'vega-lite/src/axis.js' {
  declare module.exports: $Exports<'vega-lite/src/axis'>;
}
declare module 'vega-lite/src/bin.js' {
  declare module.exports: $Exports<'vega-lite/src/bin'>;
}
declare module 'vega-lite/src/channel.js' {
  declare module.exports: $Exports<'vega-lite/src/channel'>;
}
declare module 'vega-lite/src/compile/axis.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/axis'>;
}
declare module 'vega-lite/src/compile/common.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/common'>;
}
declare module 'vega-lite/src/compile/compile.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/compile'>;
}
declare module 'vega-lite/src/compile/config.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/config'>;
}
declare module 'vega-lite/src/compile/data/bin.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/bin'>;
}
declare module 'vega-lite/src/compile/data/colorrank.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/colorrank'>;
}
declare module 'vega-lite/src/compile/data/data.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/data'>;
}
declare module 'vega-lite/src/compile/data/filter.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/filter'>;
}
declare module 'vega-lite/src/compile/data/formatparse.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/formatparse'>;
}
declare module 'vega-lite/src/compile/data/formula.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/formula'>;
}
declare module 'vega-lite/src/compile/data/nonpositivenullfilter.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/nonpositivenullfilter'>;
}
declare module 'vega-lite/src/compile/data/nullfilter.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/nullfilter'>;
}
declare module 'vega-lite/src/compile/data/source.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/source'>;
}
declare module 'vega-lite/src/compile/data/stackscale.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/stackscale'>;
}
declare module 'vega-lite/src/compile/data/summary.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/summary'>;
}
declare module 'vega-lite/src/compile/data/timeunit.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/timeunit'>;
}
declare module 'vega-lite/src/compile/data/timeunitdomain.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/data/timeunitdomain'>;
}
declare module 'vega-lite/src/compile/facet.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/facet'>;
}
declare module 'vega-lite/src/compile/layer.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/layer'>;
}
declare module 'vega-lite/src/compile/layout.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/layout'>;
}
declare module 'vega-lite/src/compile/legend.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/legend'>;
}
declare module 'vega-lite/src/compile/mark/area.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/area'>;
}
declare module 'vega-lite/src/compile/mark/bar.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/bar'>;
}
declare module 'vega-lite/src/compile/mark/line.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/line'>;
}
declare module 'vega-lite/src/compile/mark/mark.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/mark'>;
}
declare module 'vega-lite/src/compile/mark/point.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/point'>;
}
declare module 'vega-lite/src/compile/mark/rule.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/rule'>;
}
declare module 'vega-lite/src/compile/mark/text.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/text'>;
}
declare module 'vega-lite/src/compile/mark/tick.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/mark/tick'>;
}
declare module 'vega-lite/src/compile/model.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/model'>;
}
declare module 'vega-lite/src/compile/scale.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/scale'>;
}
declare module 'vega-lite/src/compile/unit.js' {
  declare module.exports: $Exports<'vega-lite/src/compile/unit'>;
}
declare module 'vega-lite/src/config.js' {
  declare module.exports: $Exports<'vega-lite/src/config'>;
}
declare module 'vega-lite/src/data.js' {
  declare module.exports: $Exports<'vega-lite/src/data'>;
}
declare module 'vega-lite/src/datetime.js' {
  declare module.exports: $Exports<'vega-lite/src/datetime'>;
}
declare module 'vega-lite/src/encoding.js' {
  declare module.exports: $Exports<'vega-lite/src/encoding'>;
}
declare module 'vega-lite/src/facet.js' {
  declare module.exports: $Exports<'vega-lite/src/facet'>;
}
declare module 'vega-lite/src/fielddef.js' {
  declare module.exports: $Exports<'vega-lite/src/fielddef'>;
}
declare module 'vega-lite/src/filter.js' {
  declare module.exports: $Exports<'vega-lite/src/filter'>;
}
declare module 'vega-lite/src/legend.js' {
  declare module.exports: $Exports<'vega-lite/src/legend'>;
}
declare module 'vega-lite/src/mark.js' {
  declare module.exports: $Exports<'vega-lite/src/mark'>;
}
declare module 'vega-lite/src/scale.js' {
  declare module.exports: $Exports<'vega-lite/src/scale'>;
}
declare module 'vega-lite/src/shorthand.js' {
  declare module.exports: $Exports<'vega-lite/src/shorthand'>;
}
declare module 'vega-lite/src/sort.js' {
  declare module.exports: $Exports<'vega-lite/src/sort'>;
}
declare module 'vega-lite/src/spec.js' {
  declare module.exports: $Exports<'vega-lite/src/spec'>;
}
declare module 'vega-lite/src/stack.js' {
  declare module.exports: $Exports<'vega-lite/src/stack'>;
}
declare module 'vega-lite/src/timeunit.js' {
  declare module.exports: $Exports<'vega-lite/src/timeunit'>;
}
declare module 'vega-lite/src/transform.js' {
  declare module.exports: $Exports<'vega-lite/src/transform'>;
}
declare module 'vega-lite/src/type.js' {
  declare module.exports: $Exports<'vega-lite/src/type'>;
}
declare module 'vega-lite/src/util.js' {
  declare module.exports: $Exports<'vega-lite/src/util'>;
}
declare module 'vega-lite/src/validate.js' {
  declare module.exports: $Exports<'vega-lite/src/validate'>;
}
declare module 'vega-lite/src/vega.schema.js' {
  declare module.exports: $Exports<'vega-lite/src/vega.schema'>;
}
declare module 'vega-lite/src/vl.js' {
  declare module.exports: $Exports<'vega-lite/src/vl'>;
}
declare module 'vega-lite/test/compile/axis.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/axis.test'>;
}
declare module 'vega-lite/test/compile/common.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/common.test'>;
}
declare module 'vega-lite/test/compile/compile.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/compile.test'>;
}
declare module 'vega-lite/test/compile/config.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/config.test'>;
}
declare module 'vega-lite/test/compile/data.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data.test'>;
}
declare module 'vega-lite/test/compile/data/datatestutil.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data/datatestutil'>;
}
declare module 'vega-lite/test/compile/data/filter.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data/filter.test'>;
}
declare module 'vega-lite/test/compile/data/formatparse.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data/formatparse.test'>;
}
declare module 'vega-lite/test/compile/data/timeunit.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data/timeunit.test'>;
}
declare module 'vega-lite/test/compile/data/timeunitdomain.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/data/timeunitdomain.test'>;
}
declare module 'vega-lite/test/compile/facet.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/facet.test'>;
}
declare module 'vega-lite/test/compile/layer.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/layer.test'>;
}
declare module 'vega-lite/test/compile/layout.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/layout.test'>;
}
declare module 'vega-lite/test/compile/legend.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/legend.test'>;
}
declare module 'vega-lite/test/compile/mark/area.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/area.test'>;
}
declare module 'vega-lite/test/compile/mark/bar.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/bar.test'>;
}
declare module 'vega-lite/test/compile/mark/line.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/line.test'>;
}
declare module 'vega-lite/test/compile/mark/mark.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/mark.test'>;
}
declare module 'vega-lite/test/compile/mark/point.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/point.test'>;
}
declare module 'vega-lite/test/compile/mark/text.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/text.test'>;
}
declare module 'vega-lite/test/compile/mark/tick.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/mark/tick.test'>;
}
declare module 'vega-lite/test/compile/scale.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/scale.test'>;
}
declare module 'vega-lite/test/compile/timeunit.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/timeunit.test'>;
}
declare module 'vega-lite/test/compile/unit.test.js' {
  declare module.exports: $Exports<'vega-lite/test/compile/unit.test'>;
}
declare module 'vega-lite/test/datetime.test.js' {
  declare module.exports: $Exports<'vega-lite/test/datetime.test'>;
}
declare module 'vega-lite/test/fielddef.test.js' {
  declare module.exports: $Exports<'vega-lite/test/fielddef.test'>;
}
declare module 'vega-lite/test/filter.test.js' {
  declare module.exports: $Exports<'vega-lite/test/filter.test'>;
}
declare module 'vega-lite/test/schema.test.js' {
  declare module.exports: $Exports<'vega-lite/test/schema.test'>;
}
declare module 'vega-lite/test/spec.test.js' {
  declare module.exports: $Exports<'vega-lite/test/spec.test'>;
}
declare module 'vega-lite/test/stack.test.js' {
  declare module.exports: $Exports<'vega-lite/test/stack.test'>;
}
declare module 'vega-lite/test/timeunit.test.js' {
  declare module.exports: $Exports<'vega-lite/test/timeunit.test'>;
}
declare module 'vega-lite/test/type.test.js' {
  declare module.exports: $Exports<'vega-lite/test/type.test'>;
}
declare module 'vega-lite/test/util.js' {
  declare module.exports: $Exports<'vega-lite/test/util'>;
}
declare module 'vega-lite/test/validate.test.js' {
  declare module.exports: $Exports<'vega-lite/test/validate.test'>;
}
declare module 'vega-lite/vega-lite.js' {
  declare module.exports: $Exports<'vega-lite/vega-lite'>;
}
declare module 'vega-lite/vega-lite.min.js' {
  declare module.exports: $Exports<'vega-lite/vega-lite.min'>;
}
