// flow-typed signature: 0922faaba2a53b55e04951438504c075
// flow-typed version: <<STUB>>/vega_v^2.6.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega/scripts/schema' {
  declare module.exports: any;
}

declare module 'vega/scripts/strip-schema' {
  declare module.exports: any;
}

declare module 'vega/src/core/config' {
  declare module.exports: any;
}

declare module 'vega/src/core/HeadlessView' {
  declare module.exports: any;
}

declare module 'vega/src/core/Model' {
  declare module.exports: any;
}

declare module 'vega/src/core/schema' {
  declare module.exports: any;
}

declare module 'vega/src/core/View' {
  declare module.exports: any;
}

declare module 'vega/src/parse/axes' {
  declare module.exports: any;
}

declare module 'vega/src/parse/background' {
  declare module.exports: any;
}

declare module 'vega/src/parse/data' {
  declare module.exports: any;
}

declare module 'vega/src/parse/expr' {
  declare module.exports: any;
}

declare module 'vega/src/parse/index' {
  declare module.exports: any;
}

declare module 'vega/src/parse/interactors' {
  declare module.exports: any;
}

declare module 'vega/src/parse/legends' {
  declare module.exports: any;
}

declare module 'vega/src/parse/mark' {
  declare module.exports: any;
}

declare module 'vega/src/parse/marks' {
  declare module.exports: any;
}

declare module 'vega/src/parse/modify' {
  declare module.exports: any;
}

declare module 'vega/src/parse/padding' {
  declare module.exports: any;
}

declare module 'vega/src/parse/predicates' {
  declare module.exports: any;
}

declare module 'vega/src/parse/properties' {
  declare module.exports: any;
}

declare module 'vega/src/parse/signals' {
  declare module.exports: any;
}

declare module 'vega/src/parse/spec' {
  declare module.exports: any;
}

declare module 'vega/src/parse/streams' {
  declare module.exports: any;
}

declare module 'vega/src/parse/transforms' {
  declare module.exports: any;
}

declare module 'vega/src/scene/axis' {
  declare module.exports: any;
}

declare module 'vega/src/scene/Bounder' {
  declare module.exports: any;
}

declare module 'vega/src/scene/Builder' {
  declare module.exports: any;
}

declare module 'vega/src/scene/Encoder' {
  declare module.exports: any;
}

declare module 'vega/src/scene/GroupBuilder' {
  declare module.exports: any;
}

declare module 'vega/src/scene/legend' {
  declare module.exports: any;
}

declare module 'vega/src/scene/Scale' {
  declare module.exports: any;
}

declare module 'vega/src/scene/Transition' {
  declare module.exports: any;
}

declare module 'vega/src/scene/visit' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Aggregate' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/BatchTransform' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Bin' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/CountPattern' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Cross' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Facet' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Facetor' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Filter' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Fold' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Force' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Formula' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Geo' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/GeoPath' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Hierarchy' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Impute' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/index' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/LinkPath' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Lookup' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Parameter' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Pie' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Rank' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/screen' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Sort' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Stack' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Transform' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Treeify' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Treemap' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Voronoi' {
  declare module.exports: any;
}

declare module 'vega/src/transforms/Wordcloud' {
  declare module.exports: any;
}

declare module 'vega/src/util/format' {
  declare module.exports: any;
}

declare module 'vega/src/util/index' {
  declare module.exports: any;
}

declare module 'vega/src/util/theme-val' {
  declare module.exports: any;
}

declare module 'vega/vega' {
  declare module.exports: any;
}

declare module 'vega/vega.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega/index' {
  declare module.exports: $Exports<'vega'>;
}
declare module 'vega/index.js' {
  declare module.exports: $Exports<'vega'>;
}
declare module 'vega/scripts/schema.js' {
  declare module.exports: $Exports<'vega/scripts/schema'>;
}
declare module 'vega/scripts/strip-schema.js' {
  declare module.exports: $Exports<'vega/scripts/strip-schema'>;
}
declare module 'vega/src/core/config.js' {
  declare module.exports: $Exports<'vega/src/core/config'>;
}
declare module 'vega/src/core/HeadlessView.js' {
  declare module.exports: $Exports<'vega/src/core/HeadlessView'>;
}
declare module 'vega/src/core/Model.js' {
  declare module.exports: $Exports<'vega/src/core/Model'>;
}
declare module 'vega/src/core/schema.js' {
  declare module.exports: $Exports<'vega/src/core/schema'>;
}
declare module 'vega/src/core/View.js' {
  declare module.exports: $Exports<'vega/src/core/View'>;
}
declare module 'vega/src/parse/axes.js' {
  declare module.exports: $Exports<'vega/src/parse/axes'>;
}
declare module 'vega/src/parse/background.js' {
  declare module.exports: $Exports<'vega/src/parse/background'>;
}
declare module 'vega/src/parse/data.js' {
  declare module.exports: $Exports<'vega/src/parse/data'>;
}
declare module 'vega/src/parse/expr.js' {
  declare module.exports: $Exports<'vega/src/parse/expr'>;
}
declare module 'vega/src/parse/index.js' {
  declare module.exports: $Exports<'vega/src/parse/index'>;
}
declare module 'vega/src/parse/interactors.js' {
  declare module.exports: $Exports<'vega/src/parse/interactors'>;
}
declare module 'vega/src/parse/legends.js' {
  declare module.exports: $Exports<'vega/src/parse/legends'>;
}
declare module 'vega/src/parse/mark.js' {
  declare module.exports: $Exports<'vega/src/parse/mark'>;
}
declare module 'vega/src/parse/marks.js' {
  declare module.exports: $Exports<'vega/src/parse/marks'>;
}
declare module 'vega/src/parse/modify.js' {
  declare module.exports: $Exports<'vega/src/parse/modify'>;
}
declare module 'vega/src/parse/padding.js' {
  declare module.exports: $Exports<'vega/src/parse/padding'>;
}
declare module 'vega/src/parse/predicates.js' {
  declare module.exports: $Exports<'vega/src/parse/predicates'>;
}
declare module 'vega/src/parse/properties.js' {
  declare module.exports: $Exports<'vega/src/parse/properties'>;
}
declare module 'vega/src/parse/signals.js' {
  declare module.exports: $Exports<'vega/src/parse/signals'>;
}
declare module 'vega/src/parse/spec.js' {
  declare module.exports: $Exports<'vega/src/parse/spec'>;
}
declare module 'vega/src/parse/streams.js' {
  declare module.exports: $Exports<'vega/src/parse/streams'>;
}
declare module 'vega/src/parse/transforms.js' {
  declare module.exports: $Exports<'vega/src/parse/transforms'>;
}
declare module 'vega/src/scene/axis.js' {
  declare module.exports: $Exports<'vega/src/scene/axis'>;
}
declare module 'vega/src/scene/Bounder.js' {
  declare module.exports: $Exports<'vega/src/scene/Bounder'>;
}
declare module 'vega/src/scene/Builder.js' {
  declare module.exports: $Exports<'vega/src/scene/Builder'>;
}
declare module 'vega/src/scene/Encoder.js' {
  declare module.exports: $Exports<'vega/src/scene/Encoder'>;
}
declare module 'vega/src/scene/GroupBuilder.js' {
  declare module.exports: $Exports<'vega/src/scene/GroupBuilder'>;
}
declare module 'vega/src/scene/legend.js' {
  declare module.exports: $Exports<'vega/src/scene/legend'>;
}
declare module 'vega/src/scene/Scale.js' {
  declare module.exports: $Exports<'vega/src/scene/Scale'>;
}
declare module 'vega/src/scene/Transition.js' {
  declare module.exports: $Exports<'vega/src/scene/Transition'>;
}
declare module 'vega/src/scene/visit.js' {
  declare module.exports: $Exports<'vega/src/scene/visit'>;
}
declare module 'vega/src/transforms/Aggregate.js' {
  declare module.exports: $Exports<'vega/src/transforms/Aggregate'>;
}
declare module 'vega/src/transforms/BatchTransform.js' {
  declare module.exports: $Exports<'vega/src/transforms/BatchTransform'>;
}
declare module 'vega/src/transforms/Bin.js' {
  declare module.exports: $Exports<'vega/src/transforms/Bin'>;
}
declare module 'vega/src/transforms/CountPattern.js' {
  declare module.exports: $Exports<'vega/src/transforms/CountPattern'>;
}
declare module 'vega/src/transforms/Cross.js' {
  declare module.exports: $Exports<'vega/src/transforms/Cross'>;
}
declare module 'vega/src/transforms/Facet.js' {
  declare module.exports: $Exports<'vega/src/transforms/Facet'>;
}
declare module 'vega/src/transforms/Facetor.js' {
  declare module.exports: $Exports<'vega/src/transforms/Facetor'>;
}
declare module 'vega/src/transforms/Filter.js' {
  declare module.exports: $Exports<'vega/src/transforms/Filter'>;
}
declare module 'vega/src/transforms/Fold.js' {
  declare module.exports: $Exports<'vega/src/transforms/Fold'>;
}
declare module 'vega/src/transforms/Force.js' {
  declare module.exports: $Exports<'vega/src/transforms/Force'>;
}
declare module 'vega/src/transforms/Formula.js' {
  declare module.exports: $Exports<'vega/src/transforms/Formula'>;
}
declare module 'vega/src/transforms/Geo.js' {
  declare module.exports: $Exports<'vega/src/transforms/Geo'>;
}
declare module 'vega/src/transforms/GeoPath.js' {
  declare module.exports: $Exports<'vega/src/transforms/GeoPath'>;
}
declare module 'vega/src/transforms/Hierarchy.js' {
  declare module.exports: $Exports<'vega/src/transforms/Hierarchy'>;
}
declare module 'vega/src/transforms/Impute.js' {
  declare module.exports: $Exports<'vega/src/transforms/Impute'>;
}
declare module 'vega/src/transforms/index.js' {
  declare module.exports: $Exports<'vega/src/transforms/index'>;
}
declare module 'vega/src/transforms/LinkPath.js' {
  declare module.exports: $Exports<'vega/src/transforms/LinkPath'>;
}
declare module 'vega/src/transforms/Lookup.js' {
  declare module.exports: $Exports<'vega/src/transforms/Lookup'>;
}
declare module 'vega/src/transforms/Parameter.js' {
  declare module.exports: $Exports<'vega/src/transforms/Parameter'>;
}
declare module 'vega/src/transforms/Pie.js' {
  declare module.exports: $Exports<'vega/src/transforms/Pie'>;
}
declare module 'vega/src/transforms/Rank.js' {
  declare module.exports: $Exports<'vega/src/transforms/Rank'>;
}
declare module 'vega/src/transforms/screen.js' {
  declare module.exports: $Exports<'vega/src/transforms/screen'>;
}
declare module 'vega/src/transforms/Sort.js' {
  declare module.exports: $Exports<'vega/src/transforms/Sort'>;
}
declare module 'vega/src/transforms/Stack.js' {
  declare module.exports: $Exports<'vega/src/transforms/Stack'>;
}
declare module 'vega/src/transforms/Transform.js' {
  declare module.exports: $Exports<'vega/src/transforms/Transform'>;
}
declare module 'vega/src/transforms/Treeify.js' {
  declare module.exports: $Exports<'vega/src/transforms/Treeify'>;
}
declare module 'vega/src/transforms/Treemap.js' {
  declare module.exports: $Exports<'vega/src/transforms/Treemap'>;
}
declare module 'vega/src/transforms/Voronoi.js' {
  declare module.exports: $Exports<'vega/src/transforms/Voronoi'>;
}
declare module 'vega/src/transforms/Wordcloud.js' {
  declare module.exports: $Exports<'vega/src/transforms/Wordcloud'>;
}
declare module 'vega/src/util/format.js' {
  declare module.exports: $Exports<'vega/src/util/format'>;
}
declare module 'vega/src/util/index.js' {
  declare module.exports: $Exports<'vega/src/util/index'>;
}
declare module 'vega/src/util/theme-val.js' {
  declare module.exports: $Exports<'vega/src/util/theme-val'>;
}
declare module 'vega/vega.js' {
  declare module.exports: $Exports<'vega/vega'>;
}
declare module 'vega/vega.min.js' {
  declare module.exports: $Exports<'vega/vega.min'>;
}
