const PREFIX = "PLAY";
const FULFILLED = "FULFILLED";
const FAILED = "FAILED";
const CANCELED = "CANCELED";

export const SET_SERVER = `${PREFIX}/SET_SERVER`;

export const FETCH_SERVER = `${PREFIX}/FETCH_SERVER`;
export const FETCH_SERVER_FULFILLED = `${PREFIX}/FETCH_SERVER_${FULFILLED}`;
export const FETCH_SERVER_FAILED = `${PREFIX}/FETCH_SERVER_${FAILED}`;
export const FETCH_SERVER_CANCELED = `${PREFIX}/FETCH_SERVER_${CANCELED}`;

export const KILL_SERVER = `${PREFIX}/KILL_SERVER`;
export const KILL_SERVER_FULFILLED = `${PREFIX}/KILL_SERVER_${FULFILLED}`;
export const KILL_SERVER_FAILED = `${PREFIX}/KILL_SERVER_${FAILED}`;
export const KILL_SERVER_CANCELED = `${PREFIX}/KILL_SERVER_${CANCELED}`;

export const FETCH_KERNEL_SPECS = `${PREFIX}/FETCH_KERNEL_SPECS`;
export const FETCH_KERNEL_SPECS_FULFILLED = `${PREFIX}/FETCH_KERNEL_SPECS_${FULFILLED}`;
export const FETCH_KERNEL_SPECS_FAILED = `${PREFIX}/FETCH_KERNEL_SPECS_${FAILED}`;
export const FETCH_KERNEL_SPECS_CANCELED = `${PREFIX}/FETCH_KERNEL_SPECS_${CANCELED}`;

export const SET_ACTIVE_KERNEL = `${PREFIX}/SET_ACTIVE_KERNEL`;
export const RESTART_KERNEL = `${PREFIX}/RESTART_KERNEL`;

export const ACTIVATE_KERNEL = `${PREFIX}/ACTIVATE_KERNEL`;
export const ACTIVATE_KERNEL_FULFILLED = `${PREFIX}/ACTIVATE_KERNEL_${FULFILLED}`;
export const ACTIVATE_KERNEL_FAILED = `${PREFIX}/ACTIVATE_KERNEL_${FAILED}`;
export const ACTIVATE_KERNEL_CANCELED = `${PREFIX}/ACTIVATE_KERNEL_${CANCELED}`;

export const INTERRUPT_KERNEL = `${PREFIX}/INTERRUPT_KERNEL`;
export const INTERRUPT_KERNEL_FULFILLED = `${PREFIX}/INTERRUPT_KERNEL_${FULFILLED}`;
export const INTERRUPT_KERNEL_FAILED = `${PREFIX}/INTERRUPT_KERNEL_${FAILED}`;
export const INTERRUPT_KERNEL_CANCELED = `${PREFIX}/INTERRUPT_KERNEL_${CANCELED}`;

export const KILL_KERNEL = `${PREFIX}/KILL_KERNEL`;
export const KILL_KERNEL_FULFILLED = `${PREFIX}/KILL_KERNEL_${FULFILLED}`;
export const KILL_KERNEL_FAILED = `${PREFIX}/KILL_KERNEL_${FAILED}`;
export const KILL_KERNEL_CANCELED = `${PREFIX}/KILL_KERNEL_${CANCELED}`;

export const SUBMIT_BINDER_FORM = `${PREFIX}/SUBMIT_BINDER_FORM`;

export const SET_SOURCE = `${PREFIX}/SET_SOURCE`;
export const SET_SHOW_PANEL = `${PREFIX}/SET_SHOW_PANEL`;
export const SET_SERVER_ID = `${PREFIX}/SET_SERVER_ID`;
export const SET_CURRENT_KERNEL_NAME = `${PREFIX}/SET_CURRENT_KERNEL_NAME`;
