// @flow

// Generated by `lerna ls --json`
//
// With new packages, we'll want to run this again, and add to ignores
// Instead of opting for a fully discovered setup from the monorepo, I've opted
// for this package to work when used outside of the monorepo.
//
// Developers still have to use the same babel setup as us.
const lernaModules = [
  {
    name: "ansi-to-react",
    version: "2.0.6",
    private: false
  },
  {
    name: "@nteract/commutable",
    version: "4.0.1",
    private: false
  },
  {
    name: "@nteract/commuter-frontend",
    version: "5.0.0",
    private: false
  },
  {
    name: "@nteract/core",
    version: "5.0.1",
    private: false
  },
  {
    name: "@nteract/display-area",
    version: "4.1.1",
    private: false
  },
  {
    name: "@nteract/dropdown-menu",
    version: "0.1.2",
    private: false
  },
  {
    name: "@nteract/editor",
    version: "7.0.4",
    private: false
  },
  {
    name: "enchannel-zmq-backend",
    version: "6.0.10",
    private: false
  },
  {
    name: "fs-observable",
    version: "2.1.0",
    private: false
  },
  {
    name: "@nteract/markdown",
    version: "1.1.0",
    private: false
  },
  {
    name: "@nteract/mathjax",
    version: "1.0.0",
    private: false
  },
  {
    name: "@nteract/messaging",
    version: "4.0.0",
    private: false
  },
  {
    name: "@nteract/notebook-app-component",
    version: "1.0.0",
    private: false
  },
  {
    name: "@nteract/notebook-preview",
    version: "7.1.1",
    private: false
  },
  {
    name: "@nteract/octicons",
    version: "0.2.0",
    private: false
  },
  {
    name: "@nteract/presentational-components",
    version: "0.0.1",
    private: false
  },
  {
    name: "rx-binder",
    version: "2.0.0",
    private: false
  },
  {
    name: "rx-jupyter",
    version: "3.0.1",
    private: false
  },
  {
    name: "@nteract/styles",
    version: "1.0.1",
    private: false
  },
  {
    name: "@nteract/timeago",
    version: "3.4.9",
    private: false
  },
  {
    name: "@nteract/transform-dataresource",
    version: "3.0.2",
    private: false
  },
  {
    name: "@nteract/transform-geojson",
    version: "3.1.0",
    private: false
  },
  {
    name: "@nteract/transform-model-debug",
    version: "3.1.0",
    private: false
  },
  {
    name: "@nteract/transform-plotly",
    version: "3.1.6",
    private: false
  },
  {
    name: "@nteract/transform-vdom",
    version: "2.1.0",
    private: false
  },
  {
    name: "@nteract/transform-vega",
    version: "3.1.0",
    private: false
  },
  {
    name: "@nteract/transforms-full",
    version: "5.1.1",
    private: false
  },
  {
    name: "@nteract/transforms",
    version: "4.1.1",
    private: false
  },
  {
    name: "@nteract/types",
    version: "2.0.0",
    private: false
  },
  {
    name: "@nteract/vega-embed2",
    version: "1.0.1",
    private: false
  },
  {
    name: "@nteract/webpack-configurator",
    version: "1.0.2",
    private: false
  },
  {
    name: "@nteract/commuter",
    version: "5.2.0",
    private: false
  },
  {
    name: "nteract",
    version: "0.8.6",
    private: true
  },
  {
    name: "@nteract/nbextension",
    version: "0.4.5",
    private: true
  },
  {
    name: "@nteract/notebook-on-next",
    version: "2.0.9",
    private: false
  },
  {
    name: "@nteract/play",
    version: "1.4.9",
    private: false
  },
  {
    name: "@nteract/showcase",
    version: "0.1.20",
    private: false
  },
  {
    name: "nteract-on-jupyter",
    version: "1.6.1",
    private: false
  }
];

module.exports = {
  lernaModules
};
